const STORAGE = browser.storage.local;

const FilterType = Object.freeze({
	BLOCKED_USERS: 0,
	TITLE_REGEXS: 1,
	NAME_REGEXS: 2,
	COMMENT_REGEXS: 3,
	EXCLUDED_USERS: 4
});

const RegExType = Object.freeze({
	CASE_INSENSITIVE: 0,
	CASE_SENSITIVE: 1
});

const YTContext = Object.freeze({
	HOME: 0,
	VIDEO: 1,
	SEARCH: 2,
	TRENDING: 3,
	CHANNEL_HOME: 4,
	CHANNEL_VIDEOS: 5,
	RECOMMENDED: 6,
	OTHER: 7
});

const ConfigId = Object.freeze({
	CONFIG_PAGE_DESIGN: 0,
	CONFIG_ADVANCED_VIEW: 1,
	CONTENT_BLOCK_BTN_VISIBILITY: 2,
	CONTENT_BLOCK_VIDEOS_ON_VIDEOPAGE_VISIBILITY: 3,
	CONTENT_BLOCK_BTN_COLOR: 4,
	CONTENT_BLOCK_BTN_SIZE: 5,
	CONTENT_ANIMATION_SPEED: 6,
	USE_POPUP: 7
});
